pivnet_token: ((pivnet_token)) # [R] PivNet Access Token
git_token: ((git_token)) # [R] Your github token
git_url: https://github.com/rahul-kj/pcf-concourse-pipelines # [R] Pipelines github repo
git_branch: develop
git_username: ((git_username)) # [R] Your github username

iaas_type: vsphere-esxi # azure-hyperv|vsphere-esxi|aws-xen-hvm|openstack-kvm|vcloud-esxi|google-kvm

## Ops Manager installation meta data
ops_mgr_host: ((ops_mgr_host)) # [R] Ops Manager FQDN, ex: opsmgr.example.com
ops_mgr_usr: ((ops_mgr_usr)) # [R] Ops Manager admin user
ops_mgr_pwd: ((ops_mgr_pwd)) # [R] Ops Manager admin password

debug: false

product_name: p-appdynamics
product_identifier: appdynamics
product_version: ^4\.4\..*$

dependency_product_tiles: 'cf'

product_properties: |
  ---
  ".properties.org":
    value: appdynamics-org
  ".properties.space":
    value: appdynamics-space
  ".properties.apply_open_security_group":
    value: true
  ".properties.allow_paid_service_plans":
    value: false
  ".properties.appdynamics_service_broker_enable_global_access_to_plans":
    value: true
  ".properties.app_uri":
    value: appdynamics-service-broker
  ".properties.appd_plans":
    value:
    - plan-name:
      plan-description:
      account-name:
      account-access-key:
      host-name:
      port:
      ssl-enabled:

product_resources: |
  deploy-all:
    instance_type:
      id: "micro"

product_network_azs: |
  network:
    name:
  other_availability_zones:
    - name:
    - name:
  singleton_availability_zone:
    name:

errands_to_disable:
