resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

resources:
- name: govc
  type: github-release
  source:
    user: vmware
    repository: govmomi
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: om-cli
  type: github-release
  source:
    user: pivotal-cf
    repository: om
    access_token: ((git_token)) ## Optional: Removing this will cause you to hit the rate limit

- name: pipelines-repo
  type: git
  source:
    uri: ((git_url))
    branch: ((git_branch))
    username: ((git_username))
    password: ((git_token))

- name: ops-manager
  type: pivnet
  source:
    api_token: ((pivnet_token))
    product_slug: ops-manager
    product_version: ((opsman_product_version))

- name: concourse-trigger-gist
  type: git
  source:
    uri: ((gist_url))
    branch: master
    username: ((git_username))
    password: ((git_token))

jobs:

- name: delete-installation
  plan:
  - aggregate:
    - get: pipelines-repo
    - get: govc
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      params:
        globs:
        - "*om-linux*"
    - get: concourse-trigger-gist
    - get: ops-manager
      params:
        globs: []
        save: true
      trigger: true

  - task: delete-products
    file: pipelines-repo/tasks/delete-products/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_HOST: ((ops_mgr_host))
      OPS_MGR_USR: ((ops_mgr_usr))
      OPS_MGR_PWD: ((ops_mgr_pwd))

  - task: bump-timestamp
    file: pipelines-repo/tasks/gist-update/task.yml
    params:
      DEBUG: ((debug))
      CI_USERNAME: ((ci_username))
      CI_EMAIL_ADDRESS: ((ci_email_address))

  - put: concourse-trigger-gist
    params: {repository: updated-concourse-trigger-gist}

- name: delete-ops-manager
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [delete-installation]
    - get: govc
      passed: [delete-installation]
      params:
        globs:
        - "*linux_amd64*"
    - get: om-cli
      passed: [delete-installation]
      params:
        globs:
        - "*om-linux*"
    - get: concourse-trigger-gist
      trigger: true
      passed: [delete-installation]

  - task: delete-ops-manager
    file: pipelines-repo/tasks/delete-opsman/task.yml
    params:
      DEBUG: ((debug))
      OPS_MGR_IP: ((ops_mgr_ip))
      GOVC_INSECURE: 1
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
      GOVC_PASSWORD: ((vcenter_pwd))

- name: unpause-install-pipeline
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [delete-ops-manager]
    - get: concourse-trigger-gist
      trigger: true
      passed: [delete-ops-manager]

  - task: change-pipeline-state
    file: pipelines-repo/tasks/change-pipeline-state/task.yml
    params:
      DEBUG: ((debug))
      CONCOURSE_USERNAME: ((concourse_user))
      CONCOURSE_PASSWD: ((concourse_pwd))
      ATC_EXTERNAL_URL: ((concourse_url))
      PIPELINE_NAME: ((install_pipeline_name))
      TEAM_NAME: ((team_name))
      PIPELINE_STATE: ((install_pipeline_state))

- name: pause-reinstall-pipeline
  plan:
  - aggregate:
    - get: pipelines-repo
      passed: [unpause-install-pipeline]
    - get: concourse-trigger-gist
      trigger: true
      passed: [unpause-install-pipeline]

  - task: change-pipeline-state
    file: pipelines-repo/tasks/change-pipeline-state/task.yml
    params:
      DEBUG: ((debug))
      CONCOURSE_USERNAME: ((concourse_user))
      CONCOURSE_PASSWD: ((concourse_pwd))
      ATC_EXTERNAL_URL: ((concourse_url))
      PIPELINE_NAME: ((reinstall_pipeline_name))
      TEAM_NAME: ((team_name))
      PIPELINE_STATE: ((reinstall_pipeline_state))
